
ROOM_DEFINITION = 4
VALID_USA_CANADA_MEXICO_PHONE_NUMBER_LENGTH = 10

LITEHOUSE = 'LITEHOUSE'
LUSTRON = 'LUSTRON'

HOME_DIRECTORY = '/Users/mars/'     # TODO Switch from MacOS to ZimaBaord file directory structure

MASTER_BEDROOM = 'MASTER_BEDROOM'
MASTER_BEDROOM_X = [1770]           # X pixel location of upper left corner
MASTER_BEDROOM_Y = [245]
MASTER_BEDROOM_X_WIDTH = [505]   
MASTER_BEDROOM_Y_HEIGHT = [580]
MAX_AREA_INDEX_MASTER_BEDROOM = 1
MASTER_BEDROOM_RECT_AREAS = [[MASTER_BEDROOM_X[0], MASTER_BEDROOM_Y[0], MASTER_BEDROOM_X_WIDTH[0], MASTER_BEDROOM_Y_HEIGHT[0]],]

MASTER_BATHROOM = 'MASTER_BATHROOM'
MASTER_BATHROOM_X = [1365, 1365]           # X pixel location of upper left corner
MASTER_BATHROOM_Y = [410, 622]
MASTER_BATHROOM_X_WIDTH = [368, 270]    #TODO UPDATE 340 
MASTER_BATHROOM_Y_HEIGHT = [392, 392]
MAX_AREA_INDEX_MASTER_BATHROOM = 2
MASTER_BATHROOM_RECT_AREAS = [[MASTER_BATHROOM_X[0], MASTER_BATHROOM_Y[0], MASTER_BATHROOM_X_WIDTH[0], MASTER_BATHROOM_Y_HEIGHT[0]], \
                              [MASTER_BATHROOM_X[1], MASTER_BATHROOM_Y[1], MASTER_BATHROOM_X_WIDTH[1], MASTER_BATHROOM_Y_HEIGHT[1]]]

MAMMOTH_BRIGHT_GRREN = '#03C04A'       #'background-color: #03C04A'

class GlobalConstants:

    if __name__ == "__main__":
        print("Using GlobalConstants.py")
