
ROOM_DEFINITION = 4
VALID_USA_CANADA_MEXICO_PHONE_NUMBER_LENGTH = 10

HOME_DIRECTORY = '/Users/mars/'     # TODO Switch from MacOS to ZimaBaord file directory structure

MASTER_BEDROOM = "MASTER_BEDROOM"
MASTER_BEDROOM_X = [1770]           # X pixel location of upper left corner
MASTER_BEDROOM_Y = [245]
MASTER_BEDROOM_X_WIDTH = [505]   
MASTER_BEDROOM_Y_HEIGHT = [580]
MASTER_BEDROOM_RECT_AREAS = [MASTER_BEDROOM_X, MASTER_BEDROOM_Y, MASTER_BEDROOM_X_WIDTH, MASTER_BEDROOM_Y_HEIGHT]

MASTER_BATHROOM = "MASTER_BATHROOM"
MASTER_BATHROOM_X = [1365]           # X pixel location of upper left corner
MASTER_BATHROOM_Y = [410]
MASTER_BATHROOM_X_WIDTH = [368]   
MASTER_BATHROOM_Y_HEIGHT = [392]
MASTER_BATHROOM_RECT_AREAS = [MASTER_BATHROOM_X, MASTER_BATHROOM_Y, MASTER_BATHROOM_X_WIDTH, MASTER_BATHROOM_Y_HEIGHT]

MAMMOTH_BRIGHT_GRREN = '#03C04A'       #'background-color: #03C04A'

class GlobalConstants:

    if __name__ == "__main__":
        print("Using GlobalConstants.py")
